### ISSUE TITLE
MacOs support

### ISSUE THREAD

**Issue by phljh** [sygslhy/image-io#4]
Hello, is it possible to use this package on macos platform?

**Comment by sygslhy** [comment]
Hello thank your for using cxx-image-io package, yes, theoretically it can support macos, that is also my idea too initially , the only reason I didn't start this track is I didn't have a mac laptop :), it was difficult to test compiling without mac because it is a C++ binding project.
I recently borrowed an old mac air book, I will try to prepare a package on macos, let me get back to you sooner for the result.

**Comment by sygslhy** [comment]
Hello, I tried with mac book, we can support the macos x86_64 and arm64, I am finishing the CI to build the python packages automatically, it will be ready in short time.
Thanks for you suggestion.

**Comment by sygslhy** [comment]
v0.1.0 is released on PYPI,  https://pypi.org/project/cxx-image-io/0.1.0/ which supports macOS now.
