### ISSUE TITLE
How to install from source distribution ?

### ISSUE THREAD

**Issue by Yplnb** [sygslhy/image-io#6]
Hello, 
I tried to install from source distribution on the other arm Linux, not the x86_64, but it seems that the package search the other external libs as jpeg, png and tiff as dependencies. But I can’t figure out the whole dependencies libraries list to install before.

maybe that isn’t currently in officially supported planning. But can you share the third party libraries you uses?

besides is it possible to include the external libraries code to source distribution?

**Comment by sygslhy** [comment]
Hello,
Thanks very much for using **cxx-image-io**.
Yes, you are right, we have some external third-party libraries as https://github.com/sygslhy/image-io-libs here.
for binding project we need to rebuild these libs with -fPIC flag.

For you second question, I had some techenique issue that the find_package in one of dependency **cxx-image** looks for the third-party libraries pre-installed in Linux. currently my solution is to reinstall my -fPIC's libraries on Linux and override them, then pip installation from source distribution.

But I think it is always good if I could fusion the 2 git-repo to one.

**Comment by sygslhy** [comment]
Hello , 
v1.0.0 release was just published, which includes the support of aarch64 Linux , now I think you can download wheels instead of source code . 
In addition, the sdist can be build because I fusion third party libs source code into the build system. 
you may just build it with gcc and nasm . 

Don’t hesitate to contact me if you still have some questions. Thanks 🙏 

best regards

**Comment by Yplnb** [comment]
Thank you for your quick response  ,  I will try the new version.

**Comment by Yplnb** [comment]
The new version works for me. Thank you.
